/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ***************************************************************** *************
 */

#include <stdint.h>
#include<string.h>
#include "STM32F401CCUx.h"
#include "stm32f401ccux_gpio_driver.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
volatile uint8_t state = 0;
void delay(uint32_t n){
	for(int i = 0; i<n; i++);
}

void EXTI0_IRQHandler(void){
	// handle the interrupt
	delay(10000);
	GPIO_IRQ_Handling(GPIO_PIN_NO_0);
    state =! state;

}

int main(void)
{
    /* Loop forever */
	gpio_handle_t LED; // create a structure variable [LED is the Varibale of gpio_handle_t  Structure]
	gpio_handle_t SWITCH;
	memset(&LED , 0 , sizeof(LED));
	memset(&SWITCH , 0 , sizeof(SWITCH));
	LED.pGPIOx = GPIOA;  // select the port
	LED.gpio_config.gpio_PinNumber = GPIO_PIN_NO_6;  // select pin num
	LED.gpio_config.gpio_PinMode  = GPIO_MODE_OUT; // output mode
	LED.gpio_config.gpio_PinSpeed = SPEED_LOW; // low speed switching
	LED.gpio_config.gpio_PinOtype = GPIO_OTYPE_PP;  //  PUSHPULL
	LED.gpio_config.gpio_PinPupdControl = GPIO_NO_PUPD; // no pull up or pull down

	////// switch configuration /////////
	SWITCH.pGPIOx = GPIOA;
	SWITCH.gpio_config.gpio_PinNumber = GPIO_PIN_NO_0;
	SWITCH.gpio_config.gpio_PinMode  = GPIO_IT_FT;
	SWITCH.gpio_config.gpio_PinPupdControl = GPIO_PU;
	// init GPIO
	GPIO_PeriClockControl(GPIOA , ENABLE);
	GPIO_INIT(&LED);
    GPIO_INIT(&SWITCH);


    //////////  IRQ Configurations /////////
    GPIO_IRQ_IT_CONFIG(IRQ_NUMBER_EXTI0, ENABLE);
    GPIO_PRIORITY_CONFIG(IRQ_NUMBER_EXTI0 , 15);



	for(;;)
	{
		if(state)
		{
			GPIO_Write_to_GPIOPIN(GPIOA, GPIO_PIN_NO_6, SET);
			delay(250000);
			GPIO_Write_to_GPIOPIN(GPIOA, GPIO_PIN_NO_6, RESET);
			delay(250000);
		}

	}
}
