/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ***************************************************************** *************
 */

#include <stdint.h>
#include<string.h>
#include "STM32F401CCUx.h"
#include "stm32f401ccux_gpio_driver.h"
#include "systick.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    gpio_handle_t LED;

    memset(&LED, 0, sizeof(LED));

    LED.pGPIOx = GPIOA;
    LED.gpio_config.gpio_PinNumber = GPIO_PIN_NO_6;
    LED.gpio_config.gpio_PinMode = GPIO_MODE_OUT;
    LED.gpio_config.gpio_PinSpeed = SPEED_LOW;
    LED.gpio_config.gpio_PinOtype = GPIO_OTYPE_PP;
    LED.gpio_config.gpio_PinPupdControl = GPIO_NO_PUPD;

    GPIO_PeriClockControl(GPIOA, ENABLE);
    GPIO_INIT(&LED);

    SysTick_Init(SYSTICK_CLKSOURCE_INTERNAL);

    while(1)
    {
        GPIO_Write_to_GPIOPIN(GPIOA, GPIO_PIN_NO_6, SET);
        SysTick_DelayMs(1000);

        GPIO_Write_to_GPIOPIN(GPIOA, GPIO_PIN_NO_6, RESET);
        SysTick_DelayMs(1000);
    }
}
